WedSpread/WedSpread/Models/Question.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Project1.Models
{
    //questions class
    public class Question
    {
        //attributes for the class with gets and sets
        public int iNumber { get; set; }
        public string sQuestion { get; set; }
        public string sName { get; set; }
        public string dDate { get; set; }
        public string sAnswer { get; set; }

        //constructor for the class
        public Question(int iNum)
        {
            iNumber = iNum;
        }
    }


}

WedSpread/WedSpread/Models/Questions.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WedSpread.Models
{
    [Table("Questions")]
    public class Questions
    {
        [Key]
        public int? QuestionID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }

        [ForeignKey("Freelancers")]
        public int? FreelancerID { get; set; }

        [ForeignKey("Users")]
        public int? UserID { get; set; }
    }
}

WedSpread/WedSpread/Controllers/FreeLanceController.cs
using WedSpread.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Project1.Controllers
{
    public class FreeLanceController : Controller
    {
        private IS403Project2Context db = new IS403Project2Context();

        public User myUser = new WedSpread.Models.User();
        
        public User GetUsers()
        {
            
            if (User.Identity.IsAuthenticated)
            {
                string myEmail = User.Identity.Name;

                myUser = db.Users.SqlQuery(
                            "SELECT * " +
                            "From Users " +
                            "where Users.UserEmail = '" + myEmail + "'"
                            ).FirstOrDefault();

                if (myUser == null)
                {
                    myUser.UserID = 0;
                    return myUser;
                }
                else
                {
                    return myUser;
                }

            }
            else
            {
                myUser.UserID = 0;

                return myUser;
            }
        }
        
       

        // GET: FreeLance
        public ActionResult Index()
        {
            IEnumerable<Freelancer> freelancer = db.Freelancers.ToList();  

            return View(freelancer);
        }

        // GET: FreelancerBio
        public ActionResult Bio(int id)
        {
            Freelancer freelancer = db.Freelancers.Find(id);
            User userID = new WedSpread.Models.User();
            userID = GetUsers();
            freelancer.UserID = userID.UserID;

            return View(freelancer);
        }

        public ActionResult Elevated()
        {
            //adding data to temp data to pass to viewbag
            TempData["name"] = "Elevated-Films";
            TempData["picture"] = "Elivated Films full white.jpg";
            TempData["bio"] = "A simple, professional, and affordable videography company for all of your events. " +
                        "We offer a comprehensive experience to capture your moments from every angle. Reaching " +
                        "new heights of event filmography, the sky truly is the limit.";
            TempData["portfolio"] = "http://elevated-films.com";
            TempData["faqs"] = "Elevated-Films";

            //redirecting to bio method to display
            return RedirectToAction("Bio");
        }

        public ActionResult Photographer()
        {
            //question object with data
            TempData["name"] = "Look It Photography";
            TempData["picture"] = "profile.jpg";
            TempData["bio"] = "I'm a Salt Lake County, Utah-based photographer who loves capturing the small and simple beauties " +
                "of life. I believe that photography has emotion, and a power to capture the goodness of life. " +
                "Photos allow people to experience and reflect on life in ways often overlooked in our rushed world. " +
                "My passion is to capture details and stories through unique and compelling images. " +
                "The world is an amazing place, and my hope is to uplift and enrich the lives of those around me.";
            TempData["portfolio"] = "https://www.lookitphotography.com/";
            TempData["faqs"] = "Look It Photography";

            //redirecting to bio method to display
            return RedirectToAction("Bio");
        }

        public ActionResult Molly()
        {
            //question object with data
            TempData["name"] = "Molly in the Mineshaft";
            TempData["picture"] = "Molly1.jpg";
            TempData["bio"] = "Molly in the Mineshaft was founded in 2014 in Provo, Utah while its members " +
                        "were attending college and performing with other bands. Their purpose is to " +
                        "uplift, entertain, and inspire people of all ages through high-energy, diverse music. " +
                        "The band’s music reveals their wide range of musical influences and features flavors " +
                        "of contemporary folk, bluegrass, blues, jazz, Celtic, and rock. " +
                        "Members of the band have performed throughout North America and Europe, " +
                        "including the United States, Mexico, Croatia, France, Switzerland, and Spain. " +
                        "Their audiences range from Elementary school children to international dignitaries.";
            TempData["portfolio"] = "https://mollyinthemineshaft.com/";
            TempData["faqs"] = "Molly in the Mineshaft";

            //redirecting to bio method to display
            return RedirectToAction("Bio");
        }

        public ActionResult Questions()
        {
            return PartialView("Questions");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PostQuestions(FormCollection form)
        {
            Question question = new Question();
            if (ModelState.IsValid)
            {
                int userID = Convert.ToInt16(form["UserID"].ToString());
                question.User = db.Users.Find(userID);

                int freelancerid = Convert.ToInt16(form["FreelancerID"].ToString());
                question.Freelancer = db.Freelancers.Find(freelancerid);

                question.Question1 = form["Question"].ToString();
                
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Bio", new { id = freelancerid });
            }


            return View("Index");
        }
    }
}

WedSpread/WedSpread/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WedSpread.Models;

namespace WedSpread.Controllers
{
    public class QuestionsController : Controller
    {
        private IS403Project2Context db = new IS403Project2Context();

        // GET: Questions
        public ActionResult Index(int id)
        {
            IEnumerable<Question> FreeQuestions = db.Database.SqlQuery<Question>("SELECT * " +
                 "FROM Questions " +
                 "WHERE FreelancerID = '" + id + "'").AsEnumerable();

            return View(FreeQuestions);
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            ViewBag.FreelancerID = new SelectList(db.Freelancers, "FreelancerID", "FreelancerName");
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserEmail");
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "QuestionID,Question1,Answer,FreelancerID,UserID")] Question question, int fID)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FreelancerID = new SelectList(db.Freelancers, "FreelancerID", "FreelancerName", question.FreelancerID);
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserEmail", question.UserID);
            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.FreelancerID = new SelectList(db.Freelancers, "FreelancerID", "FreelancerName", question.FreelancerID);
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserEmail", question.UserID);
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FormCollection form)
        {
            Question question = new Question();

            if (ModelState.IsValid)
            {
                question.QuestionID = Convert.ToInt16(form["QuestionID"].ToString());
                question.FreelancerID = Convert.ToInt16(form["FreelancerID"].ToString());
                question.UserID = Convert.ToInt16(form["UserID"].ToString());
                question.Answer = form["Answer"].ToString();
             
                db.Database.ExecuteSqlCommand(
                    "Update Questions " +
                    "Set Questions.Answer = '" + question.Answer + "' " +
                    "where Questions.QuestionID = '" + question.QuestionID + "'"
                    );

                db.SaveChanges();
                return RedirectToAction("Index", new { id = question.FreelancerID });
            }
            ViewBag.FreelancerID = new SelectList(db.Freelancers, "FreelancerID", "FreelancerName", question.FreelancerID);
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserEmail", question.UserID);
            return View(question);
        }

        // GET: Questions/Delete/5
        public ActionResult Delete(int? id, int fID)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int fID)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = fID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WedSpread/WedSpread/Views/Shared/AnswerForm.cshtml
<!--Answer reply form-->
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Post Your Answer</h3>
            <form name="contactform" method="post" action="">
                <div class="row">
                    <div class="form-group">
                        <div class="col-xs-12 col-sm-3 col-md-3">
                            <input type="text" class="form-control" name="qName" maxlength="50" size="30" id="qName" placeholder="Name">
                        </div>

                    </div>
                </div>

                <div class="row" style="padding-top: 15px;">
                    <div class="form-group">
                        <div class="col-xs-6">
                            <textarea name="comments" class="form-control message" maxlength="1000" cols="25" rows="6" id="contact" placeholder="Write your answer here"></textarea>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-4" style="padding-top: 15px;">
                        <div class="col-xs-4 col-sm-offset-4 text-center center-block">
                            <button type="reset" value="submit" class="btn btn-primary" style="background-color: #3885c9; width: 10em;" id="panel-content">Submit</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

WedSpread/WedSpread/Views/Shared/Questions.cshtml
<!--Question form-->
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Questions?</h3>
            <form name="contactform" method="post" action="">
                <div class="row">
                    <div class="form-group">
                        <div class="col-xs-12 col-sm-3 col-md-3">
                            <input type="text" class="form-control" name="qName" maxlength="50" size="30" id="qName" placeholder="Name">
                        </div>

                    </div>
                </div>

                <div class="row" style="padding-top: 15px;">
                    <div class="form-group">
                        <div class="col-xs-6">
                            <textarea name="comments" class="form-control message" maxlength="1000" cols="25" rows="6" id="contact" placeholder="Write your question here"></textarea>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-4" style="padding-top: 15px;">
                        <div class="col-xs-4 col-sm-offset-4 text-center center-block">
                            <button type="reset" value="submit" class="btn btn-primary" style="background-color: #3885c9; width: 10em;" id="panel-content">Submit</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

WedSpread/WedSpread/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WEDSPREAD</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WEDSPREAD", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Freelancers", "Index", "FreeLance")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (User.Identity.IsAuthenticated == true)
                    {
                        if (WedSpread.Controllers.HelperController.GetRole() == 2)
                        {
                            <li>@Html.ActionLink("MyQuestions", "Index", "Questions", new { id = WedSpread.Controllers.HelperController.GetUser() }, null)</li>
                        }
                    }
                   
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - WEDSPREAD</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>